# Generated by Django 4.2.7 on 2023-11-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="technical_passport",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="technical_passport_back",
            field=models.ImageField(
                default="ваше_значение_по_умолчанию",
                help_text="Загрузите фото",
                upload_to="documents/",
                verbose_name="Технический паспорт задния сторона",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="technical_passport_face",
            field=models.ImageField(
                default=1,
                help_text="Загрузите фото",
                upload_to="documents/",
                verbose_name="Технический паспорт передния сторона",
            ),
            preserve_default=False,
        ),
    ]
