# Generated by Django 4.2.7 on 2023-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0002_remove_vehicle_technical_passport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boltpayment",
            name="additional_charges",
            field=models.FloatField(default=0, verbose_name="Доплата"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="bolt_commission",
            field=models.FloatField(verbose_name="Комиссия БОЛТ"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="bonus",
            field=models.FloatField(default=0, verbose_name="Бонусы"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="cancellation_fee",
            field=models.FloatField(default=0, verbose_name="Плата за отмену"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="cash_collected",
            field=models.FloatField(default=0, verbose_name="Наличные"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="compensations",
            field=models.FloatField(default=0, verbose_name="Компенсации"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="final_payout_bolt",
            field=models.FloatField(default=0, verbose_name="Финальная выплата БОЛТ"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="gross_earnings",
            field=models.FloatField(default=0, verbose_name="Брутто"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="refunds",
            field=models.FloatField(default=0, verbose_name="Возврат заказчику"),
        ),
        migrations.AlterField(
            model_name="boltpayment",
            name="tips",
            field=models.FloatField(default=0, verbose_name="Чаявые"),
        ),
    ]
