# Generated by Django 4.2.7 on 2023-11-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0005_alter_uberpayment_week_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uberpayment",
            name="week_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="uberpayment",
            name="week_start",
            field=models.DateField(),
        ),
    ]
