# Generated by Django 4.2.7 on 2023-11-17 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0006_alter_uberpayment_week_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="rental_price",
            field=models.FloatField(
                default=0,
                help_text="Ведите цену аренды",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена аренды",
            ),
        ),
    ]
