# Generated by Django 4.2.7 on 2023-11-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0007_alter_vehicle_rental_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boltpayment",
            name="bolt_commission",
            field=models.FloatField(default=0, verbose_name="Комиссия БОЛТ"),
        ),
    ]
