# Generated by Django 4.2.7 on 2023-11-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0008_alter_boltpayment_bolt_commission"),
    ]

    operations = [
        migrations.AddField(
            model_name="boltpayment",
            name="park_commission_bolt",
            field=models.FloatField(default=13, verbose_name="Комиссия автопарка Bolt"),
        ),
        migrations.AddField(
            model_name="uberpayment",
            name="park_commission_uber",
            field=models.FloatField(default=11, verbose_name="Комиссия автопарка Uber"),
        ),
        migrations.CreateModel(
            name="FinalPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(verbose_name="Номер недели"),
                ),
                ("week_start", models.DateField(verbose_name="Начало недели")),
                ("week_end", models.DateField(verbose_name="Конец недели")),
                (
                    "final_payout_bolt",
                    models.FloatField(verbose_name="Финальная выплата БОЛТ"),
                ),
                (
                    "final_payout_uber",
                    models.FloatField(verbose_name="Финальная выплата УБЕР"),
                ),
                ("total_payout", models.FloatField(verbose_name="Общая выплата")),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_payouts",
                        to="taxi_app.driver",
                        verbose_name="Водитель",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="finalpayout",
            constraint=models.UniqueConstraint(
                fields=("week_number", "week_start", "week_end", "driver"),
                name="unique_final_payout",
            ),
        ),
    ]
