# Generated by Django 4.2.7 on 2023-11-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0009_boltpayment_park_commission_bolt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalpayout",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="final_payouts",
                to="taxi_app.vehicle",
                verbose_name="Автомобиль",
            ),
        ),
    ]
