# Generated by Django 4.2.7 on 2023-11-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0010_finalpayout_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("final_payout_uber", models.FloatField(default=0)),
                ("final_payout_bolt", models.FloatField(default=0)),
                ("total_payout", models.FloatField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to="taxi_app.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_reports",
                        to="taxi_app.vehicle",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FinalPayout",
        ),
        migrations.AddConstraint(
            model_name="weeklyreport",
            constraint=models.UniqueConstraint(
                fields=("week_number", "week_start", "week_end", "driver"),
                name="unique_weekly_report",
            ),
        ),
    ]
