# Generated by Django 4.2.7 on 2023-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0011_weeklyreport_delete_finalpayout_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boltpayment",
            name="park_commission_bolt",
        ),
        migrations.RemoveField(
            model_name="uberpayment",
            name="park_commission_uber",
        ),
        migrations.AddField(
            model_name="driver",
            name="park_commission_bolt",
            field=models.FloatField(
                default=0.13, verbose_name="Комиссия автопарка Bolt"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="park_commission_uber",
            field=models.FloatField(
                default=0.11, verbose_name="Комиссия автопарка Uber"
            ),
        ),
    ]
