# Generated by Django 4.2.7 on 2023-11-17 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0012_remove_boltpayment_park_commission_bolt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boltpayment",
            old_name="driver_phone",
            new_name="phone_number",
        ),
    ]
