# Generated by Django 4.2.7 on 2023-11-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0014_alter_driver_park_commission_bolt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uberpayment",
            name="final_payout_uber",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Финальная выплата УБЕР",
            ),
        ),
    ]
