# Generated by Django 4.2.7 on 2023-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0015_alter_uberpayment_final_payout_uber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boltpayment",
            name="final_payout_bolt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Финальная выплата БОЛТ",
            ),
        ),
    ]
