# Generated by Django 4.2.7 on 2023-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0016_alter_boltpayment_final_payout_bolt"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_rented",
            field=models.BooleanField(
                default=True, verbose_name="Арендуется ли автомобиль"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="final_payout_bolt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="final_payout_uber",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="total_payout",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
