# Generated by Django 4.2.7 on 2023-11-24 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0017_vehicle_is_rented_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
