# Generated by Django 4.2.7 on 2023-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0018_driver_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="uuid",
            field=models.CharField(
                help_text="Введите UUID", max_length=100, verbose_name="UUID"
            ),
        ),
    ]
