# Generated by Django 4.2.7 on 2023-11-24 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0019_alter_driver_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
    ]
