# Generated by Django 4.2.7 on 2023-11-25 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi_app", "0020_alter_driver_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="rental_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ведите цену аренды",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена аренды",
            ),
        ),
    ]
